version: '3.7'

services:
#    inert:
#        container_name: inert
#        image: inert:latest
#        volumes:
#            - "inert:/code/data"
#        environment:
#            - DEBUG=$DEBUG
#            - TOKEN=$TOKEN
#            - REDDIT_ID=$REDDIT_ID
#            - REDDIT_SECRET=$REDDIT_SECRET
    inert-redis:
        container_name: inert-redis
        image: redis
        ports:
            - 6379:6379
        env_file: 
            - .env
#volumes:
#    inert:
#        name: inert
